export type AdminStadiumRecord = {
  id: string;
  name: string;
  slug: string;
  description: string;
  address: string;
  city: string;
  area: string;
  morningPrice: number;
  eveningPrice: number;
  depositAmount: number | null;
  contactPhone: string | null;
  contactWhatsapp: string | null;
  coverImage: string | null;
  sportType?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  shamCashId?: string | null;
  shamCashQrImage?: string | null;
  isActive: boolean;
  isSuspended: boolean;
  owner: { id: string; firstName: string; lastName: string; phone: string };
  _count: { bookings: number; reviews: number };
};
